// 언어팩 선언.
$.lang = {};

$.lang.kr = {
  0: 'RIX',
  1: '팀원',
  2: '로드맵',
  3: 'ICO',
  4: '블로그',
  5: '백서',
  14: '세계 최초의, 고유자산을 갖는 탈중앙화 AI 암호화화폐 투자 플랫폼.<br/><br/><br/>',
  15: '프리세일',

  20: 'Pain point',
  21: '암호화화폐 시장에서 개인투자자가 수익을 내기 위해서는 특별한 솔루션이 필요합니다.',
  22: '지난 1년간 비트코인은 700% 이상 성장했지만 개인투자자는 개인, 시장, 환경등',
  23: '여러가지 요인에 의해 수익에 집중할 수록 이 시장에서 높은 수익을 기대할 수 없는 모순된 상황을 가지고 있습니다.',
  24: '시장은 24시간 작동하고,  당신은 시장을 충분히 모니터링할 수 없고, 매매 타이밍을 잡기 어렵습니다.',
  25: '코인시장은 서킷브레이크가 없고, 상한가와 하한가가 없습니다. 개인투자자는 심리적으로 위축될 수 밖에 없습니다.',
  26: '법적으로, 증권이 아니기 때문에 담합이나 부당거래를 법적으로 제제하지 않습니다. 이 때문에 당신은 더 취약합니다.',

  27: 'Solution',
  28: '개인 투자자산의 가치를 극대화하기 위해 다음의 3가지 차원의 솔루션을 제공합니다.',
  29: '기계학습에 의한 AI투자 시스템',
  30: 'Rix는 ICO 직후 암호화 화폐를 고유자산으로 편입합니다. 이 자산은 AI 투자 머신에 의해서 지속적으로 투자 수익을 발생시킵니다. Rix는 RNN 및 CNN에 의한 4중의 인공지능 레이어를 통해 통제 되어 투자종목과 거래소 비중, 금액, 타이밍 등 모든 것이 자동화 되어 있으며, 독립적 채산단위를 가진 수많은 투자모듈들로 이루어져 있습니다. Rix는 비트코인의 연간 수익률인 720%와 전업개인투자자의 최고 수익률인 연 6000% 사이의 수익률을 목표로 합니다. 비전업 개인투자자에겐 꿈과 같은 수치일수 있으나, 일간 수익률로 환산할 시  0.671%로 현재의 상한 하한이 없이 24시간 거래가 이뤄지는 우상향 시장에서 24시간 내내 자체 학습에 의해 투자를 수행하는 AI모듈로서는 매우 보수적인 수익률 입니다.',
  31: 'Rix의 지속적 성장을 위한 ICD',
  32: 'AI는 자산을 증가시키며, Rix의 자체 ICD(Incentive Centered Design)를 통해 모두에게 그 이익이 전달 됩니다. 모든 플레이어는 스스로 자신의 이익을 추구하기만 하면 상대방의 이익을 보장하는 매커니즘으로 디자인되어 모두가 훌륭한 투자 수익을 얻을 수 있는 암호화 화폐 플랫폼 입니다. 플레이어는 Rix는 ICO 참여자 및 중장기 투자자, 단기투자자, 신탁투자자로 구성 됩니다. <br/>ICD는 조금 어려운 개념이지만 간단히 설명하면 다음과 같습니다.  광범위한 지역을 청소하는 청소부와 먹이를 보다 쉽게 구하기 원하는 까마귀, 쓰레기를 올리면 먹이가 나오는 쓰레기통을 가지고 한 재미있는 실험이 있습니다. 이 실험에서 까마귀는 먹이를 위해 넓은 지역의 쓰레기를 모아오고 청소부는 쓰레기통에 까마귀의 보상을 지속적으로 채워넣음으로 서로의 이익을 달성하게 됩니다. Rix는 태환 서비스를 실시하여 ICO직후부터 투자위험구간을 최소화하며 코인의 장기적 생존성과 수익성을 안정적으로 추구하도록 디자인 되었습니다.',
  33: 'DAO에 의한 투명한 운영',
  34: 'RIx는 DAO를 통해 투명하게 자산을 관리하고 분배합니다. 또한 Rix의 DAO는 중요한 결정사항의 발생시 모두의 투표를 통해 결정하게 되므로 RIx의 투표 시스템을 통해 당신이 원하는 Rix를 만들어나갈 수 있습니다. 따라서 소액, 비전업, 개인 투자자의 이익을 전적으로 추구하고 실현합니다.',

  35: 'How it Works',
  36: 'AI플랫폼에 의한 투자성과 극대화, DAO를 통한 투명한 관리에 의한 개인투자자 보호가 Rix의 운영철학입니다.',
  37: 'Rix는 두가지의 자산가치 향상 방법을 가지고 있습니다.',

  38: 'System',
  39: 'Rix는 세계 최초의 자산가치를 보유한, AI에 의한 투자 및 자산관리 플랫폼입니다.',
  40: 'AI투자 시스템은 4단계의 계층구조를 가지고 있으며, 뉴럴네트워크 기반의 3차원 AI의사결정 엔진을 가지고 있습니다.',
  41: '4계층 AI투자 시스템',
  42: '3차원 AI의사결정 엔진',

  43: 'Road map',
  44: 'Rix 로드맵',

  45: 'ICO',
  46: 'RIX의 ICO는 프리세일과 정식 ICO로 나눠 진행 될 예정이며 프리세일은 5%의 보너스가 주어집니다.',
  47: 'RIX는 자산가치를 지니는 코인으로서 5%의 보너스는 자산가치를 지니지 않는 코인 대비 실질적인 보상이 됩니다.',

  48: '프리세일',
  49: '2018년 2월중 시작',
  50: '정식 ICO',
  51: '2018년 3 ~ 4월중 시작',
  52: '가격(1ETH 당 RIX)',
  53: '최소 투자금',
  54: '0.1ETH',
  55: '프리세일 - 105,000 (프리세일 보너스 -5%)',
  56: '개인 투자 제한',
  57: '100ETH',
  58: 'ICO - 100,000',
  59: '소프트캡',
  60: '6,000ETH',
  61: '*Ref. Rix당 비트코인 매입 가치는 70%',
  62: '하드캡',
  63: '40,000ETH',

  64: 'Token and fund distribution',
  65: 'RIX는 ICO 모금액(최대 40,000 ETH)의 70% 금액으로 기축 암호화 화폐(비트코인 등)를 매입하여, 고유 자산으로 예치 합니다.',
  66: '어드바이저, 마케팅, 바운티, 개발자 등의 초기 분배를 제외한 미공개분은 전량 에어드랍에 사용 됩니다.',
  68: 'Our Team',
  69: 'Core Members',
  70: "Contact Us",
  71: "Private policy",
  72: "Terms&amp;Condition",
  73: "Media Kit",
  74: "Advisory Board"
};

$.lang.en = {
  0: "RIX",
  1: "TEAM",
  2: "ROAD MAP",
  3: "ICO",
  4: "BLOG",
  5: "WHITE PAPER",
  14: "The world first decentrlized AI cryptocurrency investment platform With the intrinsic asset.",
  15: "Pre-sale",

  20: "Pain point",
  21: "In the Cryptocurrency market,<br/>it is not easy for private investors to achieve their target rate of return.",
  22: "Notwithstanding the fact that Bitcoin’s value has grown more than 700% over the past year,",
  23: "private investors are placed in an ironic situation where the more they focus on making profits, the lower rate of return they end up with due to various individual, market, and environmental factors.",
  24: "You are having a disadvantage of insufficient amount of time and investment know-how that you need to analyze the market and chart.Furthermore, the rapidly-changing market trend makes it difficult for you to make rational investment decisions.",
  25: "Since there is no circuit break in place in the Cryptocurrency market, the market price tends to significantly fluctuate. Also, the trade can occur 24 hour-a-day and the absence of relevant regulations allows big capitals to have a great deal of impact on the market.",
  26: "Investing through the chart analysis is an investment know-how more ideal for the stock market, and it is less likely to make an accurate prediction by solely relying on historical data.",

  27: "Solution",
  28: "We provide the following three-dimensional solution to maximize the value of your investment assets",
  29: "AI investment system built around machine learning technology",
  30: "Rix adds the Cryptocurrency to its intrinsic asset portfolio shortly after ICO. AI investment machines invest these assets to continuously generate returns. Rix is controlled by four artificial intelligence layers including RNN and CNN, which automates all investment related decisions such as the percentage of exchange, amount, and timing. It is made up of numerous investment modules making profits independently from each other.Rix aims to achieve the rate of return between 720%, the annual rate of return of Bitcoin, and 6000%, the highest return ever achieved by a professional private investor. This 0.671%, when converted to the daily rate of return, may seem an unrealistic number to non-professional private investors at a glance but they may actually find it very conservatively targeted in light of the current Cryptocurrency market constantly	moving upward and running 24 hour a day let alone the fact that it is not obstructed by upper or lower limit of the price movement.",
  31: "ICD Designed for the Continuous Growth of Rix",
  32: "AI increases assets and Rix's self-developed ICD (Incentive Centered Design) distributes returns to participants. It is a Cryptocurrency platform built around the mechanism where the overall profitability of the community is guaranteed by every individual member’s activity of seeking his own profit. The concept behind ICD is a little difficult to explain. But, if I do so briefly, it is as follows: There is an interesting experiment whose test subjects include a cleaner covering an extensive area of the street, crows looking for easier ways to get foods, and a trash can releasing foods in exchange for trashes. In this experiment, the crows keep bringing trashes to get foods while the cleaner regularly fills up the trash can with foods that will be used as rewards for the crows. In this way, both sides end up benefiting from each other. Rix has been designed to ensure coin’s long-term survivability and profitability by providing a withdrawal service and thus minimizing the risk zone of the investment shortly after ICO.",
  33: "Transparent Management by DAO",
  34: "Rix transparently manages and distributes assets through DAO. In addition, Rix's DAO makes important decisions only through every participant’s vote. This can allow you to tailor Rix to best serve your investment needs through Rix’s voting system. Accordingly, Rix’s sole purpose is to help non-professional private investors realize profits.",
  35: "RIX process overview",
  36: "Rix’s goal is to maximize the investment result through the use of the AI platform and protect private investors through the transparent management.",
  37: "The asset value of Rix, which individual investors become part of, has been designed to increase by two factors.",

  38: "System",
  39: "Rix is the world's first investment and asset management platform holding an asset value and run by AI.",
  40: "The AI investment system is run by a hierarchical structure of four-layers and a 3-dimensional AI decision making engine based on neural network.",
  41: "4 Level  Layer AI Investment System",
  42: "AI 3-Dimension Decision Making  Engine",

  43: "Road map",
  44: "Rix Road map",

  45: "ICO",
  46: "RIX's ICO will be divided into Pre-sale and regular ICO and 5% bonus will be granted to those participating in Pre-sale.",
  47: "Rix is the coin holding an asset value, which means 5% bonus can translate into a considerable amount of reward compared to other coins not holding the asset value.",

  48: "Pre-sale",
  49: "Feb 2018",
  50: "ICO",
  51: "Mar-Apr 2018",
  52: "Token price (Rix per 1ETH)",
  53: "Minimum purchase",
  54: "0.1ETH",
  55: "Pre-sale–105,000 (pre-sale bonus-5%)",
  56: "Individual Cap",
  57: "100ETH",
  58: "ICO – 100,000",
  59: "Soft cap",
  60: "6,000ETH",
  61: "*70% of raised fund will be spent on buying BTC.",
  62: "Hard cap",
  63: "40,000ETH",

  64: "Token and fund distribution",
  65: "Rix buys and deposit key cryptocurrencies such as BTC as intrinsic assets using 70% of the ICO funds raised.",
  66: "All undisclosed quantities except advisory, marketing, bounty and developers will be used on air drop.",
  68: "Our Team",
  69: "Core Members",
  70: "Contact Us",
  71: "Private policy",
  72: "Terms&amp;Condition",
  73: "Media Kit",
  74: "Advisory Board"
};


$.lang.ru = {
    0: "RIX",
    1: "КОМАНДА",
    2: "ДОРОЖНАЯ КАРТА",
    3: "ICO",
    4: "БЛОГ",
    5: "БЕЛАЯ БУМАГА",
    14: "первый в мире decentrlized AI криптовалюта инвестиционной платформы с собственным активом.",
    15: "Предпродажная",

    20: "Болевая точка",
    21: "На рынке криптовалюта,<br/>это не просто для частных инвесторов , чтобы достичь своей целевой нормы прибыли.",
    22: "Несмотря на то, что стоимость Bitcoin выросла более чем на 700% за прошедший год,",
    23: "частные инвесторы помещают в парадоксальную ситуацию, когда больше они сосредоточены на получении прибыли, тем ниже норма прибыли они в конечном итоге из-за различных индивидуальных, рынка и факторов окружающей среды.",
    24: "Вы испытываете недостаток недостаточного количества времени и инвестиций ноу-хау, что вам нужно проанализировать рынок и график. Кроме того, быстро меняющаяся тенденция рынка делает его трудным для вас, чтобы сделать рациональные инвестиционные решения.",
    25: "Поскольку не существует никакого разрыва цепи в месте на рынке криптовалюта, рыночная цена, как правило, значительно колебаться. Кроме того, торговля может происходить 24 часа в день, и отсутствие соответствующих правил позволяет большие капиталы иметь большое влияние на рынок.",
    26: "Инвестирование на основе анализа графика является инвестицией ноу-хау более идеальным для фондового рынка, и это менее вероятно, чтобы сделать точный прогноз на исключительно опираясь на исторические данные.",

    27: "Решение",
    28: "Мы предлагаем следующие три-пространственное решение, чтобы получить максимальную отдачу от ваших инвестиционных активов",
    29: "инвестиционная система AI построена вокруг технологии машинного обучения",
    30: "Рикс добавляет криптовалюту его собственный портфель активов вскоре после ICO. инвестиционные машины AI инвестировать эти средства для непрерывного получения прибыли. Рикс управляется четырьмя искусственными слоями разведки, включая РНН и CNN, который автоматизирует все инвестиционные решения, связанные с такими как процент обмена, количества и времени. Он состоит из многочисленных инвестиционных модулей делают прибыль независимо друг от друга. Рикс направлен на достижение уровня доходности между 720%, годовой нормой прибыли Bitcoin, и 6000%, наибольшей отдачей когда достигается профессиональным частным инвестором. Это 0,671%, при пересчете на ежедневную норму прибыли,",
    31: "ICD Предназначен для непрерывного роста Рикс",
    32: "AI увеличивает активы и самостоятельно разработанные МКБ RIX (в Стимул Centered Design) распределяет возвращается участникам. Это криптовалюта платформа, построенная вокруг механизма, где общая рентабельность сообщества гарантируется деятельности каждого отдельного члена в поисках своей собственной прибыли. Концепция МКБ немного трудно объяснить. Но, если я так кратко, это выглядит следующим образом: Существует интересный эксперимент тест которого предметы включает уборщик, охватывающий обширную область улицы, ворон ищут более простые способы, чтобы получить продукты, и мусор может выпускать продукты в обмен на громит. В этом эксперименте, вороны держать чего громит, чтобы получить пищу, а уборщик регулярно пополняет может мусор с продуктами, которые будут использоваться в качестве награды за воронами. В этом случае, обе стороны в конечном итоге выгоду друг от друга. Рикс был разработан, чтобы обеспечить монеты долгосрочную жизнеспособность и прибыльность путем предоставления услуги вывода и, таким образом, минимизируя зону риска инвестиций вскоре после ICO.",
    33: "Прозрачное управление с помощью DAO",
    34: "Рикс прозрачно управляет и распределяет средства через DAO. Кроме того, DAO RIX делает важные решения только на основе голосования каждого участника. Это позволит вам адаптировать Рикс , чтобы наилучшим образом удовлетворить ваши потребности в инвестициях через систему голосования RIX в. Соответственно, единственная цель RIX является помощь непрофессиональные частные инвесторы понимают прибыль.",
    35: "Обзор процесса RIX",
    36: "Целью RIX является максимизация инвестиционного результата за счет использования платформы AI и защиты частных инвесторов через прозрачное управление.",
    37: "Стоимость активов Rix, что индивидуальные инвесторы становятся частью, была разработана, чтобы увеличить двумя факторами.",

    38: "система",
    39: "Рикс является первым в мире инвестиций и управления активами платформы проведения стоимости активов и запустить искусственный интеллект.",
    40: "Инвестиционная система AI управляет иерархической структурой четырех слоев и 3-мерного AI принятия решений двигателя на основе нейронной сети.",
    41: "4 Уровень уровня AI Инвестиционная система",
    42: "AI 3-Dimension принятия решений двигателя",

    43: "Дорожная карта",
    44: "карта Рикс-роуд",

    45: "ICO",
    46: "ICO RIX будет разделен на предпродажный и регулярно ICO и 5% бонус будет предоставлены лицами, участвующих в предварительной продаже.",
    47: "Рикс является монетой проведения стоимости активов, что означает 5% бонуса может перевести на значительное количество вознаграждения по сравнению с другими монетами, не имеющей стоимость актива.",

    48: "Предпродажная",
    49: "Февраль 2018",
    50: "ICO",
    51: "Mar-Apr 2018",
    52: "Токен цена (Рикс в 1ETH)",
    53: "Минимальная покупка",
    54: "0.1ETH",
    55: "Предпродажная-105,000 (предпродажной бонус-5%)",
    56: "Индивидуальный Cap",
    57: "100ETH",
    58: "ICO – 100,000",
    59: "Мягкая крышка",
    60: "6,000ETH",
    61: "*70% из поднятого фонда будут потрачены на покупку BTC.",
    62: "Жесткий колпачок",
    63: "40,000ETH",

    64: "Токен и фонд распределения",
    65: "Rix покупает и кладет ключевые криптовыделения, такие как BTC, как внутренние активы, используя 70% собранных средств ICO.",
    66: "Все нераскрытые количества, за исключением консультационных, маркетинговых, щедрот и девелоперов, будут использоваться при падении воздуха.",
    68: "Наша команда",
    69: "Основные члены",
    70: "Свяжитесь с нами",
    71: "Частные политики ",
    72: "Правила&amp;условия",
    73: "Медиа - кит",
    74: "Advisory Board"
 };

$.lang.de = {
    0: "RIX",
    1: "TEAM",
    2: "FAHRPLAN",
    3: "ICO",
    4: "BLOG",
    5: "WHITE PAPER",
    14: "Die Welt decentrlized ersten AI Kryptowährung Investment-Plattform mit dem intrinsischen Wert.",
    15: "Vorverkauf",

    20: "Schmerzpunkt",
    21: "Im Kryptowährung Markt,<br/>ist es nicht leicht für private Investoren ihre Zielrendite zu erreichen.",
    22: "Notwithstanding the fact that Bitcoin’s value has grown more than 700% over the past year,",
    23: "private Investoren in einer ironischen Situation gebracht, wo je mehr sie konzentrieren Gewinne machen, die niedrigere Rendite sie aufgrund verschiedenen Einzel am Ende, Markt- und Umweltfaktoren.",
    24: "Sie haben den Nachteil einer nicht ausreichenden Menge an Zeit und Investment-Know-how, das Sie den Markt und Chart analysieren müssen. Darüber hinaus macht die sich schnell ändernden Markttrend es schwierig für Sie, rationale Investitionsentscheidungen zu treffen.",
    25: "Da es an Ort und Stelle in der Kryptowährung Markt keinen Leitungsbruch ist, neigt der Marktpreis erheblich schwankt. Auch kann der Handel 24 Stunden-a-Tag auftreten und das Fehlen einschlägiger Vorschriften ermöglicht großen Metropolen auf dem Markt eine große Wirkung zu haben.",
    26: "Die Investition durch die Chartanalyse ist ein Investment-Know-how mehr ideal für den Aktienmarkt, und es ist weniger wahrscheinlich, dass eine genaue Vorhersage von allein unter Berufung auf historische Daten zu machen.",

    27: "Lösung",
    28: "Wir bieten die folgenden dreidimensionale Lösung den Wert Ihrer Investition Vermögenswerte zu maximieren",
    29: "AI Investitionssystem um Technologie für maschinelles Lernen gebaut",
    30: "Rix fügt die Kryptowährung zu ihrem inneren Asset-Portfolio kurz nach ICO. AI Investment Maschinen investieren, um diese Vermögenswerte kontinuierlich Erträge zu generieren. Rix wird von vier künstlichen Intelligenz Schichten kontrolliert einschließlich RNN und CNN, die alle Anlageentscheidungen wie der Prozentsatz des Austausches, die Höhe und den Zeitpunkt automatisiert. Es besteht aus zahlreichen Anlagemodulen Gewinne unabhängig voneinander zu machen. Rix zielt darauf ab, die Rendite zwischen 720%, die jährliche Rendite von Bitcoin und 6000%, die höchste Rendite je von einem professionellen privaten Investor erreicht zu erreichen. Diese 0,671%, wenn sie auf die tägliche Rendite umgewandelt,",
    31: "ICD Entwickelt für das kontinuierliche Wachstum von Rix",
    32: "AI erhöht Vermögenswerte und Rix selbst entwickelte ICD (Incentive Centered Design) verteilt kehrt an die Teilnehmer. Es ist eine Kryptowährung Plattform rund um den Mechanismus gebaut, wo die Gesamtrentabilität der Gemeinschaft durch jedes einzelnes Mitglied der Tätigkeit der Suche nach seinem eigenen Gewinn garantiert. Das Konzept hinter ICD ist ein wenig schwer zu erklären. Aber wenn ich so kurz tue, ist es wie folgt: Es ist ein interessantes Experiment, dessen Tests Themen sind unter anderem eine sauberere einen umfangreichen Bereich der Straße abdeckt, Krähen für einfachere Wege suchen Lebensmittel zu bekommen, und ein Mülleimer Lebensmittel im Austausch für die Freigabe trashes. In diesem Experiment halten die Krähen trashes Lebensmittel zu bekommen zu bringen, während der Reiniger regelmäßig den Müll mit Lebensmitteln kann füllt, die als Belohnung für die Krähen verwendet werden. Auf diese Weise, beide Seiten voneinander profitieren enden. langfristige Überlebensfähigkeit und Rentabilität zu gewährleisten Münze Rix wurde entwickelt, durch einen Rückzug Service Providing und damit die Risikozone der Investition kurz nach ICO zu minimieren.",
    33: "Transparente Verwaltung von DAO",
    34: "Rix verwaltet transparent und vertreibt Vermögen durch DAO. Darüber hinaus macht Rix DAO wichtige Entscheidungen nur durch Abstimmung eines jeden Teilnehmers. Diese ermöglichen es Ihnen , Rix zuzuschneiden an Ihre Anlagebedürfnisse durch Rix des Wahlsystems zu dienen. Dementsprechend ist Rix alleinigen Zweck nicht-professionelle private Investoren Gewinne realisieren zu helfen.",
    35: "RIX Prozessübersicht",
    36: "Rix Ziel ist es, das Kapitalanlageergebnis durch die Verwendung der AI-Plattform zu maximieren und private Investoren durch das transparente Management zu schützen.",
    37: "Der Inventarwert von Rix, die einzelnen Investoren Teil geworden, wurde von zwei Faktoren zu erhöhen entworfen.",

    38: "System",
    39: "Rix ist das erste Investment und Asset Management weltweit Plattform einen Inventarwert halten und wird von AI.",
    40: "Das AI Anlagesystem wird durch eine hierarchische Struktur mit vier Schichten und eine 3-dimensionalen AI Entscheidungsfindungsmaschine basierend auf neuronalen Netzwerk ausgeführt werden.",
    41: "4 Level-Schicht AI Investitionssystem",
    42: "AI 3-Dimension Entscheidungsfindung Motor",

    43: "Straßenkarte",
    44: "Rix Straßenkarte",

    45: "ICO",
    46: "RIX ICO wird in Pre-Sale und regelmäßige ICO und 5% Bonus geteilt werden, die die in Pre-Sale-Teilnahme gewährt werden.",
    47: "Rix wird die Münze einen Vermögenswert gehalten wird, der 5% Bonus bedeutet, kann in eine beträchtliche Menge an Belohnungs übersetzen im Vergleich zu anderen Münzen nicht den Vermögenswert zu halten.",

    48: "Vorverkauf",
    49: "Februar 2018",
    50: "ICO",
    51: "Mar-April 2018",
    52: "Token Preis (Rix pro 1ETH)",
    53: "Mindestabnahme",
    54: "0.1ETH",
    55: "Pre-sale–105,000 (pre-sale bonus-5%)",
    56: "Einzelne Cap",
    57: "100ETH",
    58: "ICO – 100,000",
    59: "Weiche Mütze",
    60: "6,000ETH",
    61: "*70% angehoben Fonds für den Kauf BTC ausgegeben werden.",
    62: "Hartkappe",
    63: "40,000ETH",

    64: "Token und Fondsvertrieb",
    65: "Rix kauft und hinterlegt Schlusselkryptowahrungen wie BTC als wesentliche Vermogenswerte, wobei 70% der eingezahlten ICO-Mittel verwendet werden.",
    66: "Alle nicht genannten Mengen außer Advisory, Marketing, Bounty und Entwickler werden beim Luftabwurf verwendet.",
    68: "Unser Team",
    69: "Kern Mitglieder",
    70: "Kontaktiere uns",
    71: "Private Politik ",
    72: "Terms&amp;Condition",
    73: "Media Kit",
    74: "Advisory Board"
 };

 $.lang.zhCN = {
    0: "RIX",
    1: "球队",
    2: "道路地图",
    3: "ICO",
    4: "博客",
    5: "白皮书",
    14: "全球第一个以加密货币投资平台为核心的内置资产.<br/><br/>",
    15: "预售",

    20: "痛点",
    21: "在加密货币市场,<br/>私人投资者实现目标收益率并不容易.",
    22: "尽管过去一年比特币的价值增长了700％以上",
    23: "私人投资者被置于一个讽刺的地步，那就是他们注重利润越多，由于各种个人，市场和环境因素，他们的回报率就越低。",
    24: "你有一个缺乏时间和投资专长的缺点，你需要分析市场和图表。此外，快速变化的市场趋势使你很难作出合理的投资决策。",
    25: "由于在加密货币市场上没有电路中断，市场价格趋于显着波动。 另外，这种交易可能每天24小时发生，相关规定的缺失使得大股市对市场产生了很大的影响。",
    26: "通过图表分析进行投资是投资诀窍对于股市更为理想，单单依靠历史数据就不太可能做出准确的预测。",

    27: "解",
    28: "我们提供以下三维解决方案，以最大限度地提高您的投资资产的价值",
    29: "AI投资系统围绕机器学习技术而建立",
    30: "Rix在ICO之后不久将加密货币添加到其固有资产组合中。 AI投资机器投资这些资产以不断产生回报。 Rix由四个人工智能层（包括RNN和CNN）控制，可自动执行所有与投资有关的决策，例如交换百分比，金额和时间。 它由众多投资模块组成，彼此独立盈利.Rix的目标是实现720％的比率，比特币的年收益率和6000％，这是专业私人投资者所获得的最高回报率。 当转换为日收益率时，这个0.671％对非专业私人投资者来说可能看起来是不切实际的，但实际上，鉴于目前的加密货币市场不断向上运行，它们可能会非常保守地瞄准 一天24小时，更不用说它不受价格变动的上限或下限的阻碍。",
    31: "ICD为Rix的持续增长而设计",
    32: "AI增加资产，Rix自行开发的ICD（激励中心设计）向参与者分配回报。它是一个以机制为基础构建的加密货币平台，社区的整体盈利能力是由每个成员寻求自己利润的活动所保证的。 ICD背后的概念有点难以解释。但是，如果我简单地这样做，它是如下：有一个有趣的实验，其测试对象包括一个覆盖街道广泛区域的清洁工，乌鸦寻找更简单的方法来获取食物，垃圾桶释放食物换取象垃圾一样清除。在这个实验中，乌鸦不断地把垃圾带到食物中，而清洁工则定期用食物来填满垃圾桶，这些食物将被用来作为乌鸦的奖励。这样，双方最终都能从中受益。 Rix的设计旨在通过提供取款服务来确保硬币的长期生存能力和盈利能力，从而最大限度地减少ICO后投资的风险区域。",
    33: "透明的管理由DAO",
    34: "Rix通过DAO透明地管理和分配资产。 另外，Rix的DAO只有通过每个参与者的投票才能作出重要的决定。 这可以让您通过Rix的投票系统来调整Rix以最好地满足您的投资需求。 因此，瑞克斯的唯一目的是帮助非专业的私人投资者实现利润。",
    35: "RIX过程概述",
    36: "Rix的目标是通过使用AI平台最大化投资成果，通过透明管理保护私人投资者。",
    37: "个人投资者成为其中一员的Rix的资产价值被设计为增加两个因素。",

    38: "系统",
    39: "Rix是世界上第一个拥有资产价值并由AI运营的投资和资产管理平台。",
    40: "人工智能投资系统由四层分层结构和基于神经网络的三维人工智能决策引擎组成。",
    41: "4层级AI投资系统",
    42: "AI三维决策引擎",

    43: "路线图",
    44: "Rix 路线图",

    45: "ICO",
    46: "RIX的ICO将被划分为预售和常规ICO，并将向参与预售的用户授予5％的奖金。",
    47: "里克斯是持有资产价值的硬币，这意味着5％的奖金可以转化为相当数量的奖励，而不是持有资产价值的其他硬币。",

    48: "预售",
    49: "2018年2月",
    50: "ICO",
    51: "2018年3月至4月",
    52: "令牌价格（每1ETH的RIX）",
    53: "最低购买量",
    54: "0.1ETH",
    55: "预售105,000（预售奖金-5％）",
    56: "个人能力",
    57: "100ETH",
    58: "ICO – 100,000",
    59: "软容量",
    60: "6,000ETH",
    61: "*募集资金的70％将用于购买BTC。",
    62: "硬容量",
    63: "40,000ETH",

    64: "令牌和资金分配",
    65: "Rix使用70％的ICO资金购买和存储BTC等主要加密货币作为固有资产。",
    66: "所有未公开的数量，除咨询，市场营销，赏金和开发商以外，都将用于空投。",
    68: "我们的队伍",
    69: "核心成员",
    70: "联系我们",
    71: "私人政策",
    72: "条款与协议",
    73: "媒体工具包",
    74: "咨询委员会"
 };

 $.lang.zhTW = {
    0: "RIX",
    1: "球隊",
    2: "道路地圖",
    3: "ICO",
    4: "博客",
    5: "白皮書",
    14: "全球第一个以加密货币投资平台为核心的内置资产<br/><br/>",
    15: "預售",

    20: "痛点",
    21: "在加密貨幣市場,<br/>私人投資者實現目標收益率並不容易",
    22: "儘管過去一年比特幣的價值增長了700％以上",
    23: "私人投資者被置於一個諷刺的地步，那就是他們注重利潤越多，由於各種個人，市場和環境因素，他們的回報率就越低。",
    24: "你有一个缺乏时间和投资专长的缺点，你需要分析市场和图表。此外，快速变化的市场趋势使你很难作出合理的投资决策。",
    25: "由于在加密货币市场上没有电路中断，市场价格趋于显着波动。 另外，这种交易可能每天24小时发生，相关规定的缺失使得大股市对市场产生了很大的影响。",
    26: "通过图表分析进行投资是投资诀窍对于股市更为理想，单单依靠历史数据就不太可能做出准确的预测。",

    27: "解",
    28: "我们提供以下三维解决方案，以最大限度地提高您的投资资产的价值",
    29: "AI投资系统围绕机器学习技术而建立",
    30: "Rix在ICO之後不久將加密货币添加到其固有資產組合中。 AI投資機器投資這些資產以不斷產生回報。 Rix由四個人工智能層（包括RNN和CNN）控制，自動執行所有與投資有關的決策，例如交換百分比，金額和時間。 它由眾多投資模塊組成，彼此獨立盈利.Rix的目標是實現720％的比率，比特幣的年收益率和6000％，這是專業私人投資者所獲得的最高回報率。 當轉換為日收益率時，這個0.671％對非專業私人投資者來說可能看起來是不現實的數字，但是鑑於目前的加密貨幣市場不斷上移並運行，他們可能實際上發現它是非常保守的目標 一天24小時，更不用說它不受價格變動的上限或下限的阻礙。",
    31: "ICD為Rix的持續增長而設計",
    32: "AI增加資產，Rix自行開發的ICD（激勵中心設計）向參與者分配回報。它是一個以機制為基礎構建的加密貨幣平台，社區的整體盈利能力是由每個成員尋求自己利潤的活動所保證的。 ICD背後的概念有點難以解釋。但是，如果我簡單地這樣做，它是如下：有一個有趣的實驗，其測試對象包括一個覆蓋街道廣泛區域的清潔工，烏鴉尋找更簡單的方法獲得食物，和一個垃圾桶釋放食物換取象垃圾一樣清除。在這個實驗中，烏鴉不斷地把垃圾帶到食物中，而清潔工則定期用食物來填滿垃圾桶，這些食物將被用來作為烏鴉的獎勵。這樣，雙方最終都能從中受益。 Rix的設計旨在通過提供提款服務確保硬幣的長期生存能力和盈利能力，從而最大限度地減少ICO後投資的風險區域。",
    33: "透明的管理由DAO",
    34: "Rix通過DAO透明地管理和分配資產。 另外，Rix的DAO只有通過每個參與者的投票才能作出重要的決定。 這可以讓您通過Rix的投票系統來調整Rix以最好地滿足您的投資需求。 因此，瑞克斯的唯一目的是幫助非專業的私人投資者實現利潤。",
    35: "RIX过程概述",
    36: "Rix的目標是通過使用AI平台最大化投資成果，通過透明管理保護私人投資者。",
    37: "個人投資者成為其中一員的Rix的資產價值被設計為增加兩個因素。",

    38: "系统",
    39: "Rix是世界上第一個擁有資產價值並由AI運營的投資和資產管理平台。",
    40: "人工智能投资系统由四层分层结构和基于神经网络的三维人工智能决策引擎组成。",
    41: "4层级AI投资系统",
    42: "AI三維決策引擎",

    43: "路线图",
    44: "Rix 路线图",

    45: "ICO",
    46: "RIX的ICO将被划分为预售和常规ICO，并将向参与预售的用户授予5％的奖金。",
    47: "瑞克斯是持有資產價值的硬幣，這意味著5％的獎金可以轉化為相當數量的獎勵與其他不持有資產價值的硬幣相比。",

    48: "预售",
    49: "2018年2月",
    50: "ICO",
    51: "2018年3月至4月",
    52: "令牌价格（每1ETH的RIX）",
    53: "最低購買量",
    54: "0.1ETH",
    55: "預售105,000（預售獎金-5％）",
    56: "個人能力",
    57: "100ETH",
    58: "ICO – 100,000",
    59: "軟容量",
    60: "6,000ETH",
    61: "*募集資金的70％將用於購買BTC。",
    62: "硬容量",
    63: "40,000ETH",

    64: "令牌和資金分配",
    65: "Rix使用70％的ICO資金購買和存儲BTC等主要加密貨幣作為固有資產。",
    66: "所有未公開的數量，除諮詢，市場營銷，賞金和開發商外，都將在空投時使用。",
    68: "我們的隊伍",
    69: "核心成員",
    70: "聯繫我們",
    71: "私人政策",
    72: "條款與協議",
    73: "媒體工具包",
    74: "諮詢委員會"
 };

 $.lang.fr = {
    0: "RIX",
    1: "ÉQUIPE",
    2: "CARTE ROUTIÈRE",
    3: "ICO",
    4: "BLOG",
    5: "PAPIER BLANC",
    14: "La première plate-forme d'investissement cryptomonnaie AI décentralisée au monde Avec l'actif intrinsèque.",
    15: "Pré-vente",

    20: "point de la douleur",
    21: "Sur le marché de la cryptomonnaie,<br/>il n'est pas facile pour les investisseurs privés d'atteindre leur taux de rendement cible.",
    22: "Nonobstant le fait que la valeur de Bitcoin a augmenté de plus de 700% au cours de la dernière année,",
    23: "les investisseurs privés sont placés dans une situation ironique où plus ils se concentrent sur la réalisation de bénéfices, plus le taux de rendement est bas en raison de divers facteurs individuels, commerciaux et environnementaux.",
    24: "Vous avez le désavantage de ne pas disposer du temps et du savoir-faire nécessaires pour analyser le marché et le graphique. De plus, la tendance du marché en évolution rapide vous empêche de prendre des décisions d'investissement rationnelles.",
    25: "Comme il n'y a pas de rupture de circuit sur le marché de la cryptomonnaie, le prix du marché a tendance à fluctuer de manière significative. En outre, le commerce peut avoir lieu 24 heures sur 24 et l'absence de réglementation pertinente permet aux grands capitaux d'avoir un impact considérable sur le marché.",
    26: "Investir à travers l'analyse graphique est un savoir-faire d'investissement plus idéal pour le marché boursier, et il est moins susceptible de faire une prédiction précise en se fondant uniquement sur des données historiques.",

    27: "Solution",
    28: "Nous fournissons la solution tridimensionnelle suivante pour maximiser la valeur de vos actifs de placement",
    29: "Système d'investissement AI construit autour de la technologie d'apprentissage automatique",
    30: "Rix ajoute la Cryptomonnaie à son portefeuille d'actifs intrinsèques peu après ICO. Les machines d'investissement IA investissent ces actifs pour générer des retours en continu. Rix est contrôlé par quatre couches d'intelligence artificielle, y compris RNN et CNN, qui automatisent toutes les décisions liées à l'investissement telles que le pourcentage d'échange, le montant et le calendrier. Il est composé de nombreux modules d'investissement réalisant des profits indépendamment les uns des autres. Rix vise à atteindre le taux de rendement entre 720%, le taux de rendement annuel de Bitcoin, et 6000%, le plus haut rendement jamais réalisé par un investisseur privé professionnel. Ces 0.671%, une fois convertis au taux de rendement journalier, peuvent sembler un nombre irréaliste aux investisseurs privés non-professionnels mais ils peuvent réellement le trouver très prudemment visé à la lumière du marché courant de Crypto-monnaie se déplaçant constamment et fonctionnant 24 heures un jour sans parler du fait qu'il n'est pas obstrué par la limite supérieure ou inférieure du mouvement des prix.",
    31: "ICD conçu pour la croissance continue de Rix",
    32: "AI augmente ses actifs et l'ICD (Incentive Centered Design) développé par Rix distribue les retours aux participants. C'est une plate-forme de Cryptocurrency construite autour du mécanisme où la rentabilité globale de la communauté est garantie par l'activité de chaque membre individuel de chercher son propre profit. Le concept de l'ICD est un peu difficile à expliquer. Mais, si je le fais brièvement, c'est comme suit: Il y a une expérience intéressante dont les sujets d'essai comprennent un nettoyeur couvrant une vaste zone de la rue, les corbeaux cherchant des moyens plus faciles d'obtenir des aliments, et une poubelle des poubelles. Dans cette expérience, les corbeaux continuent d'apporter des déchets pour obtenir des aliments tandis que le nettoyeur remplit régulièrement la poubelle avec des aliments qui seront utilisés comme des récompenses pour les corbeaux. De cette façon, les deux parties finissent par bénéficier les uns des autres. Rix a été conçu pour assurer la survie et la rentabilité à long terme de la pièce en fournissant un service de retrait et ainsi minimiser la zone à risque de l'investissement peu de temps après ICO.",
    33: "Gestion transparente par DAO",
    34: "Rix gère et distribue les actifs de manière transparente via DAO. En outre, le DAO de Rix prend des décisions importantes uniquement à travers le vote de chaque participant. Cela peut vous permettre de personnaliser Rix pour répondre au mieux à vos besoins d'investissement grâce au système de vote de Rix. En conséquence, le seul but de Rix est d'aider les investisseurs privés non professionnels à réaliser des bénéfices.",
    35: "Présentation du processus RIX",
    36: "L'objectif de Rix est de maximiser les résultats d'investissement grâce à l'utilisation de la plateforme AI et de protéger les investisseurs privés grâce à une gestion transparente.",
    37: "La valeur de l'actif de Rix, dont les investisseurs individuels font partie, a été conçue pour augmenter de deux facteurs.",

    38: "Système",
    39: "Rix est la première plate-forme d'investissement et de gestion d'actifs au monde à détenir une valeur d'actif et gérée par AI.",
    40: "Le système d'investissement AI est géré par une structure hiérarchique de quatre couches et un moteur de décision AI à trois dimensions basé sur un réseau de neurones.",
    41: "Système d'investissement AI à 4 niveaux",
    42: "Moteur de décision AI à 3 dimensions",

    43: "Carte routière",
    44: "Rix La carte routière",

    45: "ICO",
    46: "L'ICO de RIX sera divisé en ICO pré-vente et régulier et un bonus de 5% sera accordé aux participants à la pré-vente.",
    47: "Rix est la pièce qui détient une valeur d'inventaire, ce qui signifie qu'un bonus de 5% peut se traduire par un montant considérable de récompense par rapport à d'autres pièces ne détenant pas la valeur de l'actif.",

    48: "Pré-vente",
    49: "Fév 2018",
    50: "ICO",
    51: "Mars-avril 2018",
    52: "Prix du jeton (Rix par 1ETH)",
    53: "Achat minimum",
    54: "0.1ETH",
    55: "Pré-vente-105 000 (bonus pré-vente-5%)",
    56: "Plafond individuel",
    57: "100ETH",
    58: "ICO – 100,000",
    59: "Soft Cap.",
    60: "6,000ETH",
    61: "* 70% des fonds recueillis seront dépensés pour l'achat de BTC.",
    62: "Hard Cap.",
    63: "40,000ETH",

    64: "Jeton et distribution de fonds",
    65: "Rix achete et depose des cryptomonnaies cles telles que BTC en tant qu'actifs intrinseques en utilisant 70% des fonds collectes par l'OIC.",
    66: "Toutes les quantites non divulguees a l'exception des avis, du marketing, de la prime et des developpeurs seront utilisees sur les largages aeriens.",
    68: "Notre équipe",
    69: "Membres principaux",
    70: "Contactez nous",
    71: "Politique privée",
    72: "termes & Condition",
    73: "Dossier de presse",
    74: "Conseil consultatif"
 };

 $.lang.es = {
    0: "RIX",
    1: "TEAM",
    2: "Hoja de ruta",
    3: "ICO",
    4: "BLOG",
    5: "PAPEL BLANCO",
    14: "La primera plataforma descentralizada de inversión en criptomoneda AI con el activo intrínseco.",
    15: "Preventa",

    20: "Punto de dolor",
    21: "En el mercado de criptomonedas,<br/> no es fácil para los inversores privados alcanzar su tasa de rendimiento objetivo.",
    22: "A pesar del hecho de que el valor de Bitcoin ha crecido más del 700% en el último año,",
    23: "los inversores privados se encuentran en una situación irónica en la que cuanto más se concentran en obtener beneficios, menor es la tasa de rentabilidad con la que terminan debido a diversos factores individuales, de mercado y ambientales.",
    24: "Está teniendo una desventaja de la cantidad insuficiente de tiempo y conocimientos de inversión que necesita para analizar el mercado y el gráfico. Además, la tendencia del mercado que cambia rápidamente hace que sea difícil para usted tomar decisiones de inversión racionales.",
    25: "Dado que no existe una interrupción de circuito en el mercado de criptomonedas, el precio de mercado tiende a fluctuar significativamente. Además, el comercio puede ocurrir las 24 horas del día y la ausencia de regulaciones relevantes permite a los grandes inversores tener un gran impacto en el mercado.",
    26: "Invertir a través del análisis de gráficos es un know-how de inversión más ideal para el mercado bursátil, y es menos probable que realice una predicción precisa basándose únicamente en datos históricos.",

    27: "Solución",
    28: "Brindamos la siguiente solución tridimensional para maximizar el valor de sus activos de inversión",
    29: "Sistema de inversión de inteligencia artificial basado en la tecnología de aprendizaje automático",
    30: "Rix agrega la criptomoneda a su cartera de activos intrínsecos poco después de ICO. Las máquinas de inversión de AI invierten estos activos para generar rendimientos continuamente. Rix está controlado por cuatro capas de inteligencia artificial que incluyen RNN y CNN, que automatiza todas las decisiones relacionadas con la inversión, como el porcentaje de intercambio, cantidad y tiempo. Se compone de numerosos módulos de inversión que obtienen ganancias de forma independiente. Rix tiene como objetivo alcanzar la tasa de rendimiento entre 720%, la tasa de rendimiento anual de Bitcoin y 6000%, el rendimiento más alto logrado por un inversor privado profesional. Este 0.671%, cuando se convierte a la tasa de rendimiento diaria, puede parecer un número poco realista para inversionistas privados no profesionales de un vistazo, pero en realidad pueden encontrarlo de manera muy conservadora a la luz del mercado actual de criptomonedas que se mueve constantemente hacia arriba y funcionando las 24 horas un día y mucho menos el hecho de que no está obstruido por el límite superior o inferior del movimiento del precio.",
    31: "ICD diseñado para el crecimiento continuo de Rix",
    32: "La IA aumenta los activos y el ICD de diseño propio de Rix (Incentive Centered Design) distribuye devoluciones a los participantes. Se trata de una plataforma de criptomoneda construida en torno al mecanismo en el que la actividad económica de cada miembro de la comunidad garantiza la rentabilidad global de la comunidad en busca de su propio beneficio. El concepto detrás de ICD es un poco difícil de explicar. Pero, si lo hago brevemente, es el siguiente: Hay un experimento interesante cuyos sujetos de prueba incluyen un limpiador que cubre un área extensa de la calle, cuervos que buscan formas más fáciles de obtener alimentos y un bote de basura que libera alimentos a cambio de basura. En este experimento, los cuervos siguen trayendo basura para obtener alimentos mientras que el limpiador llena regularmente el bote de basura con alimentos que se usarán como recompensa para los cuervos. De esta manera, ambas partes terminan beneficiándose el uno del otro. Rix ha sido diseñado para garantizar la supervivencia y la rentabilidad a largo plazo de la moneda mediante la prestación de un servicio de retirada y, por lo tanto, la minimización de la zona de riesgo de la inversión poco después de ICO.",
    33: "Gestión transparente por DAO",
    34: "Rix gestiona y distribuye de manera transparente los activos a través de DAO. Además, el DAO de Rix toma decisiones importantes solo a través del voto de cada participante. Esto puede permitirle adaptar Rix para atender mejor sus necesidades de inversión a través del sistema de votación de Rix. En consecuencia, el único propósito de Rix es ayudar a los inversores privados no profesionales a obtener ganancias.",
    35: "Visión general del proceso RIX",
    36: "El objetivo de Rix es maximizar el resultado de la inversión mediante el uso de la plataforma de inteligencia artificial y proteger a los inversores privados a través de la gestión transparente.",
    37: "El valor del activo de Rix, del que los inversores individuales forman parte, ha sido diseñado para aumentar en dos factores.",

    38: "Sistema",
    39: "Rix es la primera plataforma de inversión y gestión de activos del mundo que posee un valor de activos y es administrada por AI.",
    40: "El sistema de inversión de IA está dirigido por una estructura jerárquica de cuatro capas y un motor de toma de decisiones de IA tridimensional basado en una red neuronal.",
    41: "Sistema de inversión de IA de nivel 4",
    42: "Motor de toma de decisiones de 3 dimensiones AI",

    43: "Hoja de ruta",
    44: "Rix Hoja de ruta",

    45: "ICO",
    46: "El ICO de RIX se dividirá en Pre-venta y ICO regular y se otorgará un 5% de bonificación a aquellos que participen en la preventa.",
    47: "Rix es la moneda que contiene un valor de activo, lo que significa que un 5% de bonificación puede traducirse en una cantidad considerable de recompensa en comparación con otras monedas que no tienen el valor del activo.",

    48: "Preventa",
    49: "Feb 2018",
    50: "ICO",
    51: "Mar-Apr 2018",
    52: "Precio del token (Rix por 1ETH)",
    53: "Compra mínima",
    54: "0.1ETH",
    55: "Preventa–105,000 (Preventa prima-5%)",
    56: "Límites individuales",
    57: "100ETH",
    58: "ICO – 100,000",
    59: "Soft cap",
    60: "6,000ETH",
    61: "*El 70% del fondo recaudado se gastará en la compra de BTC.",
    62: "Hard cap",
    63: "40,000ETH",

    64: "Distribución de tokens y fondos",
    65: "Rix compra y deposita las criptomonedas clave como BTC como activos intrinsecos usando el 70% de los fondos de ICO recaudados.",
    66: "Todas las cantidades no divulgadas, excepto las de asesoria, mercadotecnia, recompensa y desarrolladores, se usaran en el envio aereo.",
    68: "Nuestro equipo",
    69: "Miembros centrales",
    70: "Contáctenos",
    71: "Política privada",
    72: "Términos y Condiciones",
    73: "Kit de medios",
    74: "Junta Asesora"
 };

 $.lang.ja = {
    0: "RIX",
    1: "TEAM",
    2: "ROAD MAP",
    3: "ICO",
    4: "BLOG",
    5: "WHITE PAPER",
    14: "資産価値を持つ世界初脫中央化AI暗号化貨幣投資プラットフォーム<br/><br/>",
    15: "先行販売",

    20: "痛みのポイント",
    21: "Cryptocurrency市場では、<br/>民間投資家はリターンの彼らの目標レートを達成することは容易ではありません。",
    22: "ビットコインの価値は、この1年で700パーセントを成長しているという事実にもかかわらず、",
    23: "個人投資家がより多くの彼らは利益を作ることに焦点を当て皮肉な状況に置かれ、彼らは様々な個人、市場、および環境要因によるもので終わるの戻り率が低いです。",
    24: "あなたは、市場やチャートを分析するのに必要な時間と投資ノウハウの不足という欠点を持っています。さらに、急速に変化する市場動向は、それは難しいあなたが合理的な投資判断を行うようになります。",
    25: "Cryptocurrency市場の場所には、回路断線がないため、市場価格が大きく変動する傾向があります。また、貿易は24時間体制発生する可能性がありますし、関連法規の不在は大きな資本が市場に与える影響の多くを持つことができます。",
    26: "チャート分析を通じて投資は株式市場のためのより理想的な投資ノウハウであり、単に過去のデータに依存することによって、正確な予測を行う可能性が低いです。",

    27: "溶液",
    28: "私たちは、あなたの投資資産の価値を最大化するために、以下の3次元ソリューションを提供します",
    29: "機械学習技術を中心に構築されたAIへの投資システム",
    30: "RixはICO直後、暗号化の貨幣を固有資産に編入します。この資産はAI投資マシンによって持続的に投資収益を発生させます。RixはRNN及びCNNによる意向の人工知能レイヤーを通じて統制、投資銘柄や取引所の割合、金額、タイミングなど、全てが自動化しており、独立採算単位を持った数多くの投資モジュールで構成されています。Rixは、ビットコインの年間収益率の720%と専業個人投資者の最高の収益率の年6000%の間の収益率を目標にします。ビチョンオプ個人投資者には夢と同じ数値日数いるが、日刊紙の収益率に換算する市0.671%で現在の上限下限がなく24時間取引が行われる右方向に上昇市場で24時間、独自の学習によって投資を遂行するAIモジュールとしては非常に保守的な収益率です。",
    31: "ICD Rixの持続的成長のために設計",
    32: "AIは、資産が増加し、Rixの自己開発ICD（インセンティブ中心設計）は、参加者に収益を分配します。これは、コミュニティの全体的な収益性を自分の利益を追求するすべての個々のメンバーの活動によって保証されているメカニズムを中心に構築されたCryptocurrencyプラットフォームです。ICDの背後にある考え方は、説明するのは少し難しいです。私はそう簡単に行う場合は、次のようにしかし、それは次のようになります。そのテストの被験者通りの広範な領域をカバークリーナーを含ま興味深い実験があり、カラスは食べ物を得るための簡単な方法を探していると、ゴミが引き換えに食糧を解放することができますゴミ。この実験では、カラスはクリーナー定期的にカラスのための報酬として使用される食品とゴミ箱をいっぱいにしながら、食べ物を得るためにゴミをもたらし続けます。この方法では、双方は互いに恩恵を受けてしまいます。Rixは、出金サービスを提供するため、まもなくICO後の投資の危険ゾーンを最小化することにより、コインの長期的存続性と収益性を確保するために設計されています。",
    33: "DAOによって透明性の高い経営",
    34: "Rixは透過的に管理し、DAOを通じて資産を配布します。また、RixのDAOは、すべての参加者の投票によって、重要な意思決定を行います。これは、あなたが最高Rixの投票システムを通して、あなたの投資ニーズに応えるためにRixを調整できるようにすることができます。したがって、Rixの唯一の目的は、非専門家の個人投資家が利益の実現に貢献することです",
    35: "RIXプロセスの概要",
    36: "Rixの目標は、AIのプラットフォームを使用して、投資結果を最大化し、透明性の高い経営を通じて個人投資家を保護することです。",
    37: "個人投資家の一部となるRixの資産価値は、二つの要因によって増加するように設計されています。",

    38: "システム",
    39: "RixはAIによって資産価値と実行を保持する世界初の投資と資産管理プラットフォームです。",
    40: "AI投資システムは、四層の階層構造とニューラルネットワークに基づく3次元AIの意思決定エンジンによって実行されます。",
    41: "4レベルのレイヤAI投資システム",
    42: "AI 3次元意思決定エンジン",

    43: "ロードマップ",
    44: "Rixロードマップ",

    45: "ICO",
    46: "RIXのICOは中古販売や定期ICOに分割されますと、5％のボーナスは先行販売に参加する者に付与されます。",
    47: "Rixは、資産価値を保持していない他の硬貨と比較して報酬のかなりの量に変換することができ、5％のボーナスを意味する資産価値を保持コインです。",

    48: "先行販売",
    49: "2018年2月",
    50: "ICO",
    51: "2018年3月-4月",
    52: "トークン価格（1ETHあたりRix）",
    53: "最低購入",
    54: "0.1ETH",
    55: "先行販売-105000（先行販売のボーナス-5％）",
    56: "個々のキャップ",
    57: "100ETH",
    58: "ICO – 100,000",
    59: "ソフトキャップ",
    60: "6,000ETH",
    61: "*調達資金の70％は、BTCの購入に費やされます。",
    62: "ハードキャップ",
    63: "40,000ETH",

    64: "トークンと資金配分",
    65: "Rixは、BTCなどの主要な暗号化された通貨を購入し、ICO資金の70％を使用して内在資産として預け入れる。",
    66: "勧告、マーケティング、賞金、開発者を除くすべての未公開数量は、エアドロップで使用されます。",
    68: "私たちのチーム",
    69: "コアメンバー",
    70: "お問い合わせ",
    71: "プライベートポリシー",
    72: "利用規約",
    73: "メディアキット",
    74: "諮問機関"
 };
